### ISSUE TITLE
package.json references derelict-ogg ~master

### ISSUE THREAD

**Issue by OlaOst** [DerelictOrg/DerelictVorbis#1]
I have a project referencing both derelict-ogg and derelict-vorbis.
After changing the dub version specification from ~master to >=1.0.0, I got 'Root package testogg contains reference to invalid package derelict-ogg' errors when running dub commands.

**Comment by mdparker** [comment]
When you change the version like that, you might have to run 'dub upgrade' afterward to make sure it pulls it down properly. Also, in which dub configuration did you make the change -- yours or the package.json in DerelictVorbis? DerelictVorbis already has a dependency on DerelictOgg, so you don't need it to your own dub configuration. I just checked and the DerelictVorbis config is specifying derelict-ogg ~master. It should have been changed long ago to 1.0.0.

I'll be pushing a fix for it soon. Once the dub registry picks it up, change your dependency to "derelict-vorbis": ">=1.0.1", remove the derelict-ogg dependency if you have one, and run 'dub upgrade' on your project. Then you should be set. If all is well, let me know so we can close this issue.

**Comment by OlaOst** [comment]
I did the change in my own config. I tried running 'dub upgrade' but that gave the same error.

After referencing derelict-vorbis 1.0.1 it works fine now though, thanks!
